[Nth 64]
GSG-G13/ntherapy-react pull request #15
Opened 2023-06-19 16:15 UTC by raghdarizq

2023-06-20 10:07 UTC, ahmedmurtaja requested changes

2023-06-20 10:07 UTC, ahmedmurtaja commented on src/components/AppointmentsModal/classes.ts
> +  // marginLeft: ' 18px',
remove commented code

2023-06-20 10:07 UTC, ahmedmurtaja commented on src/components/AppointmentsModal/index.tsx
> +          <Typography component="b">Choose Your Availability Times </Typography>
i think using heading elements ``h1,h2,...``is better than using `` b``

2023-06-20 10:07 UTC, ahmedmurtaja commented on src/pages/therapistProfile/schema.ts
> +  // to: yup
commented code

2023-06-20 12:34 UTC, aaamra commented on src/components/AppointmentsModal/index.tsx
> +                          <LocalizationProvider dateAdapter={AdapterDayjs}>
duplicated

2023-06-20 12:58 UTC, raghdarizq commented on src/components/AppointmentsModal/index.tsx
> +          <Typography component="b">Choose Your Availability Times </Typography>
It is not appropriate

2023-06-21 11:51 UTC, ahmedmurtaja approved these changes

2023-06-22 07:31 UTC, YasserAmro0 approved these changes

2023-06-22 08:26 UTC, MohannadSabaa approved these changes

2023-06-22 08:58 UTC, LinaYahya approved these changes

2023-06-22 08:58 UTC, merged