select date and Time for user and handle payment
GSG-G13/ntherapy-react pull request #17
Opened 2023-06-21 19:45 UTC by YasserAmro0

A Reservation session Form in Modal, this modal should have two tabs 
one for selecting a single appointment that suite him 
and a second tab to add A payment method

2023-06-21 20:50 UTC, ahmedmurtaja approved these changes

2023-06-22 03:29 UTC, raghdarizq approved these changes

2023-06-22 11:32 UTC, LinaYahya requested changes

2023-06-22 11:32 UTC, LinaYahya commented on .vscode/settings.json
> +    "bookappointment"
```suggestion

```

2023-06-22 11:32 UTC, LinaYahya commented on .env.development
> +    VITE_BASEURL = 'http://localhost:4000'
please revert this change

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/modal/index.tsx
> +const defaultTheme = createTheme();
we do create theme if we want to override theme style, as u don't do such a thing no need to create theme

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/modal/index.tsx
> +const Comp = ({ step, formik }: any) => {
```suggestion
const Comp = ({ step, formik }: any) => {

```
please change component name and replace any with the real type

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/modal/index.tsx
> +const SessionReservationModal = ({ open, setOpen }:any) => {
```suggestion
const SessionReservationModal = ({ open, setOpen }:Type) => {

```

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/modal/index.tsx
> +      <ThemeProvider theme={defaultTheme}>
```suggestion

```

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/payment/index.tsx
> +const stripePromise = loadStripe('pk_test_51NGyZkEFeMbkGJMBieYj5kVZnmRPzkZ5JVEe6rd4IvSOu1XAAxmN2arJ0LJMGKxFr6LNdyemP9q5tixH3RPUu3Vl00U8U0DSmt');
please add this to .env even though variables at react env is exposed everywhere, Just to be able to change this variable on different environments

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/payment/index.tsx
> +          appointment: [{ id: '1' }],
Not sure why do u add a fixed value for appointmentID

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/payment/index.tsx
> +    const fetchData = async () => {
```suggestion
    const getClientSecret = async () => {

```
For sure axios request going to fetch data, But what this request about!
Use meaningful var's naming

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/selectTime/index.tsx
> +  const message = time.length === 0 ? 'Sorry No appointments Found' : '';
Maybe we can [useMemo](https://react.dev/reference/react/useMemo) here to not calculating this value every render

2023-06-22 11:32 UTC, LinaYahya commented on src/utils/TimeRange.ts
> +const TimeRanges = (datetime:string) => {
use meaningful var name, a descriptive name explains what function is doing

2023-06-22 11:32 UTC, LinaYahya commented on src/pages/therapistProfile/index.tsx
> +import ModalComponents from '../../components/bookappointment/modal';
import from `components/`

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/selectTime/index.tsx
> +        console.error('Errorappointments intent:', error);
don't console.log error instead use snackbar to alert something went wrong

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/selectTime/index.tsx
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
```suggestion

```

2023-06-22 11:32 UTC, LinaYahya commented on src/components/bookappointment/selectTime/index.tsx
> +              sx={{ width: '100%' }}
add `disablePast`, to prevent user from selecting date from past

2023-06-22 11:32 UTC, LinaYahya commented on src/components/checkoutform/index.tsx
> +  const [open, setOpen] = useState(false);
please check `enqueSnackbar` used in signup and try to use

2023-06-22 11:32 UTC, LinaYahya commented on src/components/checkoutform/index.tsx
> +        return_url: `http://localhost:5173/therapist/${params.id}`,
Is this a required field?

2023-06-22 11:32 UTC, LinaYahya commented on src/components/checkoutform/index.tsx
> +        {isLoading ? <div className="spinner" id="spinner" /> : 'Booki'}
check [loading button](https://mui.com/material-ui/react-button/#loading-button) please

2023-06-22 11:32 UTC, LinaYahya commented on src/pages/login/validationSchema.ts
> +const validationSchema = yup.object({
why u pushed this file?

2023-06-23 15:01 UTC, MohannadSabaa approved these changes

2023-06-24 09:58 UTC, ahmedmurtaja commented
@YasserAmro0 fix conflict

2023-06-24 17:30 UTC, ahmedmurtaja commented on src/components/bookappointment/modal/index.tsx
> +import ModelStyle from '../../../pages/therapistProfile/classes';
too long path for import 
please import it from the index/create the file in the same folder

2023-06-24 17:30 UTC, ahmedmurtaja commented on src/components/bookappointment/modal/index.tsx
> +import BookAppointment from '../selectTime/index';
no need to type index here
```suggestion
import BookAppointment from '../selectTime';

```

2023-06-24 17:30 UTC, ahmedmurtaja commented on src/components/bookappointment/payment/index.tsx
> +import { Snackbar, SnackbarContent } from '@mui/material';
we will use enqueSnackbar instead

2023-06-24 21:09 UTC, ahmedmurtaja commented on src/components/bookappointment/payment/index.tsx
> +        <div>Loading...</div>
Check this [Link](https://mui.com/material-ui/react-progress/)

2023-06-24 21:11 UTC, ahmedmurtaja commented on src/components/bookappointment/selectTime/index.tsx
> +  const [value, setValue] = useState<Dayjs | null>(dayjs('2023-06-18'));
```suggestion
  const cuurentDate = dayjs().format('YYYY-MM-DD').toString();
  const [date, setDate] = useState<Dayjs | string >(dayjs(cuurentDate));

```

2023-06-24 21:21 UTC, ahmedmurtaja commented on src/components/bookappointment/modal/index.tsx
> +  switch (step) {
```suggestion
const StepComponent: React.FC<StepComponentProps> = ({ step, formik }) => {
  const components = {
    0: <BookAppointment formik={formik} />,
    1: <StripePaymentForm />,
  };

  return components[step] || null;
};

```

2023-06-24 21:31 UTC, ahmedmurtaja commented on package.json
> +    "i": "^0.3.7",
what is this package?

2023-06-25 14:59 UTC, ahmedmurtaja approved these changes

2023-06-26 05:42 UTC, ahmedmurtaja approved these changes

2023-06-26 05:43 UTC, ahmedmurtaja commented
@YasserAmro0  there  is conflict in these files

2023-06-26 07:17 UTC, LinaYahya approved these changes

2023-06-26 07:17 UTC, LinaYahya commented on src/components/checkoutform/index.tsx
> +        },
```suggestion


```

2023-06-26 07:17 UTC, LinaYahya commented on src/components/checkoutform/index.tsx
> +            : 'Booki'}
```suggestion
            : 'Book'}

```

2023-06-26 07:17 UTC, merged