Therapist profile page from user and therapist
GSG-G13/ntherapy-react pull request #23
Opened 2023-06-30 07:51 UTC by YasserAmro0

**Before anything unites some notes there** 
1 - Authorization I put it manually so I can check update
2- isEditable Wait for the back route to know true or false

 Good luck on your reivew

1. From the user perspective, the Therapist Profile page allows users to access detailed information about a therapist, such as their name, major, hourly rate, and a brief biography. Users can also view the therapist's profile image and have the option to change it by hovering over the image and clicking on the "Change Photo" button. The page provides a form to edit the therapist's name, major, and hourly rate, with the ability to save the changes. Additionally, users can reserve a session with the therapist by clicking the "Reserve a Session" button, which opens a modal for session reservation.

2. From the therapist perspective, the Therapist Profile page allows therapists to showcase their professional information. Therapists can view their own profile information, including their name, major, hourly rate, biography, and profile image. They can edit their name, major, and hourly rate by updating the form fields and saving the changes. Therapists can also modify their biography by using a rich text editor component, enabling them to add and format text content. The profile image can be changed by hovering over it and selecting a new image file.

2023-06-30 07:58 UTC, ahmedmurtaja approved these changes

2023-06-30 07:58 UTC, ahmedmurtaja commented on .env.development
> +    VITE_BASEURL = 'http://localhost:4000'
revert this change

2023-07-01 11:06 UTC, LinaYahya requested changes

2023-07-01 11:06 UTC, LinaYahya commented on src/components/index.tsx
> +import BioEditor from './therapistProfile/changeBio';
can we import all components from therapistProfile from index file?
```suggestion
import { BioEditor } from './therapistProfile/';
```

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +        headers: { Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGhlcmFwaXN0IiwidXNlcklkIjoiNSIsInRoZXJhcGlzdElkIjoiMiJ9.gGlnqHx0QN93rw87HdavQH-QN1kA3mQ6yALwl9M2L_w' },
no need to add header here

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +    setShow(!show);
IF changes saved successfully then we can setShow to false

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +          <Button
can we use muiLoadignButton here?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +          <IconButton
IconButton should rendered conditionally for profile owner only

2023-07-01 11:06 UTC, LinaYahya commented on src/components/index.tsx
> +import TextFieldEdited from './therapistProfile/textFieldWithEdited';
Are u going to use those components outside components?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/classes.ts
> +interface Type {
Why u mix types and styles at the same file?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/index.tsx
> +  const [image, setImage] = useState<string>('');
simplly all those states are exist in dataFromTjerapist, SO why to duplicate your states?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/index.tsx
> +  const [openModal, setOpenModal] = useState(false);
please use descriptive names fro your state's,
```suggestion
  const [showReservationModal, setShowReservationModal] = useState(false);

```
same for 
```js
  const [open, setOpen] = useState(false);
```

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/index.tsx
> +  const [hover, setHover] = useState(false);
use a clear names please

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +const TextFieldEdite: React.FC<Props> = ({
```suggestion
const EditableTextField: React.FC<Props> = ({

```

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +  const { enqueueSnackbar } = useSnackbar();
u can import enqueueSnackbar directly from notistack

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +
instead of declaring two functions to control mouse over create a function that toggleMouseover

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +        headers: { Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidGhlcmFwaXN0IiwidXNlcklkIjoiNSIsInRoZXJhcGlzdElkIjoiMiJ9.gGlnqHx0QN93rw87HdavQH-QN1kA3mQ6yALwl9M2L_w' },
remove headers please

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +      multiline={dataType === 'bio'}
No need, as this component is not used for bio anymore

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/index.tsx
> +            <Box
why not to move the whole box to ChangePhoto component?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +  const { enqueueSnackbar } = useSnackbar();
import enqueueSnackbar directly from notistack

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +      error={value === ''}
?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +    {editMode && <Button variant="contained" onClick={handleUpdate}>Save</Button>}
can we use a loading button here?

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +      enqueueSnackbar(error.message, { variant: 'error' });
try to fix typescript error of error.message

2023-07-01 11:06 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +  onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
```suggestion
  onChange: ChangeEventHandler<HTMLInputElement | HTMLTextAreaElement>;

```
Can u please try to fix this in your components, as well as please move interfaces to a separate files

2023-07-01 19:45 UTC, YasserAmro0 commented on src/components/therapistProfile/changeBio/index.tsx
> +          <IconButton
I handled this here 
```js
{
                  isEditable ? (
                    <BioEditor
                      textBio={textBio}
                      handleChangeTextBio={handleChangeTextBio}
                    />
                  ) : (
                    <div
                      dangerouslySetInnerHTML={{ __html: textBio }}
                      style={{
                        marginTop: '50px',
                        marginLeft: '65px',
                      }}
                    />
                  )
            }
```

2023-07-02 07:46 UTC, raghdarizq approved these changes

2023-07-02 11:41 UTC, LinaYahya requested changes

2023-07-02 11:41 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +      setShow(true);
no need as it's already true

2023-07-02 11:41 UTC, LinaYahya commented on src/components/therapistProfile/changeBio/index.tsx
> +      setShow(false);
please setShow to false after request being sent

2023-07-02 11:41 UTC, LinaYahya commented on src/components/therapistProfile/textFieldWithEdited/index.tsx
> +    setEditMode(false);
please move this after request done successfully

2023-07-02 11:41 UTC, LinaYahya commented on src/components/therapistProfile/therapistHeader/index.tsx
> +  const handleChangeName = (event: React.ChangeEvent<HTMLInputElement>) => {
can u please try to handle input changes in one modularized function

2023-07-02 14:16 UTC, LinaYahya approved these changes

2023-07-02 14:21 UTC, MohannadSabaa approved these changes

2023-07-02 14:21 UTC, merged