using useContext
GSG-G13/ntherapy-react pull request #27
Opened 2023-07-02 16:48 UTC by YasserAmro0

- create a context that holds user data and the updater function of user data, using useContext
- wrapping our app with Context Provider

2023-07-02 16:49 UTC, ahmedmurtaja commented on .env.development
> +    VITE_BASEURL = 'http://localhost:4000'
@YasserAmro0

2023-07-02 16:56 UTC, ahmedmurtaja approved these changes

2023-07-03 06:26 UTC, LinaYahya requested changes, later dismissed

2023-07-03 06:26 UTC, LinaYahya commented on src/context/index.tsx
> +        enqueueSnackbar(axiosError.message, { variant: 'error' });
no need, Why If I'm not logged in to see an error message?

2023-07-03 06:26 UTC, LinaYahya commented on src/context/index.tsx
> +const AppContext: React.FC<AppContextProps> = ({ children }) => {
rename please to userContext

2023-07-03 06:26 UTC, LinaYahya commented on src/context/contextData.ts
> +const userDataContext = createContext<UserDataContextValue>(null!);
```suggestion
const userDataContext = createContext<UserDataContextValue | null>(null);

```

2023-07-03 06:26 UTC, LinaYahya commented on src/context/index.tsx
> +  const [userData, setUserData] = useState<UserData[]>([]);
while userData is an object, why to give it initial value as an empty array, instead it can be null, more meaningfull

2023-07-03 06:26 UTC, LinaYahya commented on src/context/index.tsx
> +
can we create a loading state and if it's loading return loading instead of userDataContext?

2023-07-03 06:26 UTC, LinaYahya commented on src/context/index.tsx
> +import React, {
please rename file to userContext or authContext and export to index.ts

2023-07-03 07:12 UTC, raghdarizq approved these changes

2023-07-03 07:17 UTC, MohannadSabaa approved these changes

2023-07-03 09:20 UTC, ahmedmurtaja approved these changes

2023-07-03 09:21 UTC, merged