build: create a table dashboard for Admin
GSG-G13/ntherapy-react pull request #8
Opened 2023-06-13 11:56 UTC by raghdarizq

Created a  dashboard for Admin table include Therapist Name , Therapist CV,request Status,Options
   requirements,  using MIU .

2023-06-13 13:12 UTC, LinaYahya approved these changes

2023-06-13 13:32 UTC, YasserAmro0 approved these changes

2023-06-13 13:39 UTC, ahmedmurtaja approved these changes

2023-06-13 20:02 UTC, MohannadSabaa requested changes

2023-06-13 20:02 UTC, MohannadSabaa commented on src/components/dashboard/table/index.tsx
> +import TableMiu from '@mui/material/Table';
for cleaner code, you can import Mui components in one  line no need to import every component in a single line

2023-06-13 20:02 UTC, MohannadSabaa commented on src/components/dashboard/table/therapists/BodyTable.tsx
> +import Avatar from '@mui/material/Avatar';
The same note in comment #1

2023-06-14 07:25 UTC, MohannadSabaa approved these changes

2023-06-14 07:25 UTC, merged